# Generated by Django 5.1 on 2024-08-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sity',
            field=models.TextField(blank=True, max_length=12),
        ),
    ]
