# Generated by Django 5.1 on 2024-08-26 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0006_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
