# Generated by Django 5.1 on 2024-08-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0010_tag_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
