# Generated by Django 5.1 on 2024-09-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0011_alter_tag_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['subscriber'], name='photo_app_s_subscri_c31c09_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['subscribed_to'], name='photo_app_s_subscri_060280_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['subscriber', 'subscribed_to'], name='photo_app_s_subscri_789b93_idx'),
        ),
    ]
