# Generated by Django 5.1 on 2024-10-02 13:34

import photo_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0013_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=photo_app.models.upload_to_prefix),
        ),
    ]
